# Opens pull requests when GitHub Actions or Rust crates have updates.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      crates:
        patterns: ["*"]
